### ISSUE TITLE
Can't load the css.

### ISSUE THREAD

**Issue by hilen** [LouisBarranqueiro/hexo-theme-tranquilpeak#238]
```
[blog] hexo g                                                                                             7:41:41
INFO  Start processing
ERROR Process failed: source/_css/layout/_about.scss
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/dUser/code/blog/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/dUser/code/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/dUser/code/blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/dUser/code/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/dUser/code/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/dUser/code/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/dUser/code/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Process failed: source/_css/layout/_blog.scss
```
### Configuration

 - **Operating system with version** :  10.11.3
 - **Node version** :  v4.2.4
 - **Hexo version** :  v3.2.0
 - **Hexo-cli version** : v1.0.1
 - **Tranquilpeak version** :  v1.7.0

**Comment by LouisBarranqueiro** [comment]
Hey man, this issue is already open : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/224

**Comment by hilen** [comment]
When I replace the version 3.1.1, it's still not work. Why?

**Comment by LouisBarranqueiro** [comment]
Did you remove the `node_modules` folder? Did you edit the right line `"hexo":"^3.1.1"`  with `"hexo":"3.1.1"` and re-run `npm install`

**Comment by hilen** [comment]
Yes, I did as you said. The hexo version is 
```
hexo: 3.1.1
os: Darwin 15.4.0 darwin x64
http_parser: 2.5.0
node: 4.2.4
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e
```

But it's still no work.

**Comment by LouisBarranqueiro** [comment]
try  to replace `"hexo-renderer-ejs": "^0.1.0",` with `"hexo-renderer-ejs": "0.1.0",` and delete `node modules` folder re-run `npm install`

**Comment by hilen** [comment]
Failed too. Dude.

**Comment by LouisBarranqueiro** [comment]
come on gitter man :)

**Comment by hilen** [comment]
Thank you for your help.

**Comment by LouisBarranqueiro** [comment]
https://gitter.im/LouisBarranqueiro/hexo-theme-tranquilpeak
