### ISSUE TITLE
Cannot find module 'jsdom'

### ISSUE THREAD

**Issue by darionyaphet** [LouisBarranqueiro/hexo-theme-tranquilpeak#244]
### Configuration

 - **Operating system with version** : 
 - **Node version** :  v5.5.0 
 - **Hexo version** : 3.1.1.
 - **Hexo-cli version** : 1.0.1
 - **Tranquilpeak version** :  check out from git repo 
 

```
Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/darion.johannes.yaphet/darionyaphet.github.io/themes/tranquilpeak/scripts/tags/tabbed_codeblock.js:6:13
    at /Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:628:18)
    at /Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

**Comment by LouisBarranqueiro** [comment]
What are you trying to do?

**Comment by darionyaphet** [comment]
Hi  @LouisBarranqueiro  I try to using `hexo-theme-tranquilpeak` on 'hexo'

**Comment by LouisBarranqueiro** [comment]
yeah, I know that :D but did you install npm dependencies? when it outputs that? during `hexo s`, `hexo g`?

**Comment by darionyaphet** [comment]
sorry .. I forgot `hexo g` thanks

**Comment by AFeng521web** [comment]
hi! this bug is why
ERROR Script load failed: themes\love\scripts\tags\tabbed_codeblock.js
Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (G:\Blog\blog\node_modules\hexo\lib\hexo\index.js:219:21)
    at G:\Blog\blog\themes\love\scripts\tags\tabbed_codeblock.js:6:13
    at fs.readFile.then.script (G:\Blog\blog\node_modules\hexo\lib\hexo\index.js:232:12)
    at tryCatcher (G:\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at G:\Blog\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at G:\Blog\blog\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
INFO  Start processing
INFO  Files loaded in 1.2 s
INFO  Generated: index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2018/index.html
INFO  Generated: archives/2018/05/index.html
INFO  Generated: 2018/05/10/hello-world/index.html
INFO  5 files generated in 133 ms

**Comment by AFeng521web** [comment]
I use follow command 
1.git clone  git clone https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak.git themes/tranquilpeak
2.hexo g
3.hexo d
4.hexo s
tranquilpeak is my very favourite theme
