### ISSUE TITLE
Hexo error when running the echo server mode and generation.

### ISSUE THREAD

**Issue by twirlfog** [LouisBarranqueiro/hexo-theme-tranquilpeak#260]
### Configuration

 - **Operating system with version** : Windows_NT 6.1.7601 win32 x64 (Windows 7 x64)
 - **Node version** : 6.2.0
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.1
 - **Tranquilpeak version** : 1.7.1
 

### Actual behavior
**Hexo** error when running the echo server mode and generation.
> When you install the plugin `hexo-renderer-sass` in **Hexo** everything runs without errors.
> `hexo i hexo-renderer-sass --save`

### Expected behavior
```js
hexo g
INFO  Start processing
ERROR Process failed: source/_css/layout/_blog.scss
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (D:\github\hexo\node_modules\hexo\lib\theme\view.js:104:22)
    at View (D:\github\hexo\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\github\hexo\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\github\hexo\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\github\hexo\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\github\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\github\hexo\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (D:\github\hexo\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\github\hexo\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\github\hexo\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (D:\github\hexo\node_modules\bluebird\js\release\promise.js:628:18)
    at Promise._resolveCallback (D:\github\hexo\node_modules\bluebird\js\release\promise.js:423:57)
    at Promise._settlePromiseFromHandler (D:\github\hexo\node_modules\bluebird\js\release\promise.js:514:17)
    at Promise._settlePromise (D:\github\hexo\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\github\hexo\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\github\hexo\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (D:\github\hexo\node_modules\bluebird\js\release\promise.js:628:18)
    at D:\github\hexo\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\github\hexo\node_modules\graceful-fs\graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
...
```
Exactly the error for all 8 files in a folder `source/_css/layout/`

### Steps to reproduce the behavior
- hexo s
- hexo g

**Comment by LouisBarranqueiro** [comment]
hey buddy. it's a known issue. It come from hexo. Downgrade to hexo 3.1.1 to fix this : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/224

**Comment by LouisBarranqueiro** [comment]
The theme doesn't use hexo-renderer-sass, so it's strange that install this module fix the problem. Normaly, hexo should ignore all files and folders which start with a `_`

**Comment by twirlfog** [comment]
The developer is certainly better understood, but a different design using scss does not produce such errors. I am wrong ? Hexo fault? (sorry for my English)
Two themes tried to work, I do not remember the name. 
At home tried [fact](https://github.com/artchen/hexo-theme-fact)

**Comment by twirlfog** [comment]
You can close or remove it issue. I install `hexo-renderer-sass` for fix.

**Comment by LouisBarranqueiro** [comment]
Did you read the issue that I gave you? I'm not gonna add a unused dependency to fix a bug that come from an other module (hexo in this case). I oppened an issue on the repo : https://github.com/hexojs/hexo/issues/1793

If you wanna fix this issue temporarily : 

- downgrade to Hexo 3.1.1

or 

1. rename `source/_layout` folder in `source/_tmp` 
2. rename old folder name by the new one : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/source/_css/tranquilpeak.scss#L22-L30
