### ISSUE TITLE
Error: Cannot find module '../highlight_alias.json'

### ISSUE THREAD

**Issue by bucketzxm** [LouisBarranqueiro/hexo-theme-tranquilpeak#273]
### Configuration

 - **Operating system with version** :  Ubuntu16.04
 - **Node version** : v4.4.5
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.1
 - **Tranquilpeak version** : master
 

### Actual behavior
ERROR Script load failed: themes/hexo-theme-tranquilpeak/scripts/tags/tabbed_codeblock.js
Error: Cannot find module '../highlight_alias.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/srv/blog/node_modules/hexo-util/lib/highlight.js:6:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/srv/blog/node_modules/hexo-util/lib/index.js:8:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (/srv/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /srv/blog/themes/hexo-theme-tranquilpeak/scripts/tags/tabbed_codeblock.js:3:12
    at /srv/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/srv/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)

**Comment by LouisBarranqueiro** [comment]
Hey @bucketzxm,

What are you trying to do? What command did you enter?

**Comment by bucketzxm** [comment]
Hi @LouisBarranqueiro ,
I am just replace the theme of my blog and try `hexo server`. The server can start but there is an error like this. But it seems that the blog appearance is all right 👍

**Comment by LouisBarranqueiro** [comment]
try to run `npm install` in the theme directory.

**Comment by bucketzxm** [comment]
It seems some permission problems.  I rm the node_module dir and re-install it. Thanks ! :)

**Comment by LouisBarranqueiro** [comment]
Is it working now?
