### ISSUE TITLE
hexo s  don't running

### ISSUE THREAD

**Issue by weihai4099** [LouisBarranqueiro/hexo-theme-tranquilpeak#275]
### Configuration

 - **Operating system with version** : Linux 4.2.3-300.fc23.x86_64 linux x64
 - **Node version** : v0.10.36
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : the lasted
 - **Bower** : 1.7.9
 

### Actual behavior

[weihai@qiao blog]$ hexo s

/home/weihai/wangtian/blog/themes/tranquilpeak/node_modules/jsdom/lib/jsdom.js:3
() => `jsdom 7.x onward only works **on Node.js 4 or newer**: https://github.com/t
 ^
ERROR Script load failed: themes/tranquilpeak/scripts/tags/tabbed_codeblock.js
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/home/weihai/wangtian/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /home/weihai/wangtian/blog/themes/tranquilpeak/scripts/tags/tabbed_codeblock.js:6:13
    at /home/weihai/wangtian/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at /home/weihai/wangtian/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/weihai/wangtian/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:272:14
    at /home/weihai/wangtian/blog/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/weihai/wangtian/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/weihai/wangtian/blog/node_modules/hexo/node_modules/warehouse/node_modules/graceful-fs/graceful-fs.js:43:10
    at /usr/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at Object.oncomplete (fs.js:108:15)
**INFO  Start processing
Error: EMFILE, too many open files '/home/weihai/wangtian/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/node_modules/readdirp/stream-api.js'**
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.Module._extensions..js (module.js:473:44)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at readdir (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/node_modules/readdirp/readdirp.js:52:25)
    at FSWatcher.<anonymous> (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:355:5)
    at FSWatcher.NodeFsHandler._handleDir (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:406:18)
    at FSWatcher.<anonymous> (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/weihai/wangtian/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at Object.oncomplete (fs.js:108:15)

### According to the following steps to run
Installation

* Run git clone https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak.git
* Rename the folder in tranquilpeak and place it in themes folder of your Hexo blog
* Modify the theme in _config.yml by changing theme variable to tranquilpeak
* Complete theme/tranquilpeak/_config.yml with your information by following directives in comments
* Go in theme/tranquilpeak folder with cd themes/tranquilpeak
* Install all requirements
* Run npm install to install all NPM dependencies
* Run bower install to install all Bower dependencies
* If you want to configure the theme, please follow the user documentation

### What should I do next,Sorry,I'm a novice

**Comment by LouisBarranqueiro** [comment]
Hey @weihai4099, are you ablee to upgrade your Node version to v4? If yes, install it, and try again

**Comment by LouisBarranqueiro** [comment]
I'm waiting your answer to update requirements version.

**Comment by weihai4099** [comment]
INFO  Start processing
ERROR Process failed: source/_css/layout/_about.scss
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/home/weihai/wangtian/blog/node_modules/hexo/lib/theme/view.js:104:22)


I have update nodejs version to 6.2...But there is an error in the above..
I think about grunt .Now, I'm `npm install `again.But ,the network is not very good.  loading.....

**Comment by weihai4099** [comment]
sorry,mang error.I,don't want to try again and again

**Comment by LouisBarranqueiro** [comment]
The last error is caused by Hexo, and not the theme. the latest version of Tranquilpeak integrate a workaround to fix it.

**Comment by weihai4099** [comment]
ok,

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.8.1](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.8.0) is released and I updated the required versions :)
