### ISSUE TITLE
Script load failed: cannot find module

### ISSUE THREAD

**Issue by icecutie** [LouisBarranqueiro/hexo-theme-tranquilpeak#290]
I am setting up my github page for the first time , using hexo,I found this fabulous theme on the internet and downloaded it, but I failed with infos as follows, can you help me figure it out?
Thank you so much!
### Configuration

 - **Operating system with version** : mac os 10.11.5
 - **Node version** : v4.4.7
 - **Hexo version** : 
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** :  original  , just downloaded 

<error info -->
RROR Script load failed: themes/tranquilpeak/scripts/migrators/1.4.0.js
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (/Users/xueqingzou/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/xueqingzou/blog/themes/tranquilpeak/scripts/migrators/1.4.0.js:6:15
    at /Users/xueqingzou/blog/themes/tranquilpeak/scripts/migrators/1.4.0.js:233:3
    at /Users/xueqingzou/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/xueqingzou/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Script load failed: themes/tranquilpeak/scripts/tags/tabbed_codeblock.js
Error: Cannot find module 'hexo-util'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (/Users/xueqingzou/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/xueqingzou/blog/themes/tranquilpeak/scripts/tags/tabbed_codeblock.js:3:12
    at /Users/xueqingzou/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/xueqingzou/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
INFO  Deleted database.
INFO  Deleted public folder.
localhost:blog xueqingzou$ hexo server
ERROR Script load failed: themes/tranquilpeak/scripts/migrators/1.4.0.js
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (/Users/xueqingzou/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/xueqingzou/blog/themes/tranquilpeak/scripts/migrators/1.4.0.js:6:15
    at /Users/xueqingzou/blog/themes/tranquilpeak/scripts/migrators/1.4.0.js:233:3
    at /Users/xueqingzou/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/xueqingzou/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Script load failed: themes/tranquilpeak/scripts/tags/tabbed_codeblock.js
Error: Cannot find module 'hexo-util'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (/Users/xueqingzou/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/xueqingzou/blog/themes/tranquilpeak/scripts/tags/tabbed_codeblock.js:3:12
    at /Users/xueqingzou/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /Users/xueqingzou/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/xueqingzou/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by icecutie** [comment]
I dont know how to see hexo version , is that because my hexo haven't been installed properly?
I got this when I run "hexo v"
hexo-cli: 1.0.2
os: Darwin 15.5.0 darwin x64
http_parser: 2.5.2
node: 4.4.7
v8: 4.5.103.36
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h

**Comment by icecutie** [comment]
I just download another theme and find it works ,but I really like this theme the most!
Need your help~~~~~~
 Thank you!

**Comment by LouisBarranqueiro** [comment]
Hey @icecutie, did you download the source or built version ready for production?

**Comment by icecutie** [comment]
Now it works!
I find another download link in the description document and downloaded another version and now it works
I use "downloaded as zip " yesterday
it seems that I simply doesn't find the right version
thank you!

**Comment by LouisBarranqueiro** [comment]
No, the first time, you downloaded the source of the project. So you have to install all requirements, dependencies, and buil the theme to use it in prod. With the built version ready for production, all this stuff is already did. :)
