### ISSUE TITLE
i have an error

### ISSUE THREAD

**Issue by Ahmed-Badawy** [LouisBarranqueiro/hexo-theme-tranquilpeak#356]
i'm new to hexo but i really really like your theme. 
this error keeps popuing up:-

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EMFILE: too many open files, open 'E:_Learning & Cources_ShortCuts\EveryDay's Node\26-10-2016-Hexo\myBlog\node_modules\readdirp\stream-api.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.Module._extensions..js (module.js:564:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at readdir (E:_Learning & Cources_ShortCuts\EveryDay's Node\26-10-2016-Hexo\myBlog\node_modules\readdirp\readdirp.js:55:48)
    at FSWatcher.<anonymous> (E:_Learning & Cources_ShortCuts\EveryDay's Node\26-10-2016-Hexo\myBlog\node_modules\chokidar\lib\nodefs-handler.js:355:5)
    at FSWatcher.NodeFsHandler._handleDir (E:_Learning & Cources_ShortCuts\EveryDay's Node\26-10-2016-Hexo\myBlog\node_modules\chokidar\lib\nodefs-handler.js:406:18)
    at FSWatcher.<anonymous> (E:_Learning & Cources_ShortCuts\EveryDay's Node\26-10-2016-Hexo\myBlog\node_modules\chokidar\lib\nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (E:_Learning & Cources_ShortCuts\EveryDay's Node\26-10-2016-Hexo\myBlog\node_modules\chokidar\lib\nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by LouisBarranqueiro** [comment]
Hey @Ahmed-Badawy , please fill all fields to post an issue. It help me a lot to solve your problem :)
