### ISSUE TITLE
TypeError: jsDom.env is not a function

### ISSUE THREAD

**Issue by charsdavy** [LouisBarranqueiro/hexo-theme-tranquilpeak#430]
### Configuration
hexo: 3.2.0
hexo-cli: 1.0.3
os: Darwin 16.6.0 darwin x64
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k

```
ERROR Script load failed: themes/tranquilpeak/scripts/tags/tabbed_codeblock.js
TypeError: jsDom.env is not a function
    at /Users/dengw/hexo/themes/tranquilpeak/scripts/tags/tabbed_codeblock.js:12:7
    at /Users/dengw/hexo/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at /Users/dengw/hexo/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/dengw/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:456:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
```

How can I solve it?

**Comment by charsdavy** [comment]
API uses the correct way ： https://www.npmjs.com/package/jsdom   
and https://www.npmjs.com/package/node-jsdom

**Comment by LouisBarranqueiro** [comment]
Hi @charsdavy, what are you trying to do? Did you download the source or the production version? I guess your downloaded the source and forgot to install all the dependencies. Read the developer documentation to install them : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#installation

**Comment by charsdavy** [comment]
Thank you very mach. @LouisBarranqueiro I had solve it.
