### ISSUE TITLE
hexo server fails with errors

### ISSUE THREAD

**Issue by max-white** [LouisBarranqueiro/hexo-theme-tranquilpeak#438]
### Configuration

 - **Operating system with version** : Linux 4.83-1-MANJARO
 - **Node version** : 8.4.0
 - **Hexo version** : 3.3.8
 - **Hexo-cli version** : 1.0.3
 - **Tranquilpeak version** : 1.10.0
 

### Actual behavior
Iam currently running into the following error with the development version of the repo, the production
version runs smoothly though. npm run prod is building successfully. The errors are occuring in different modules. So far i have seen es5-ext and cssstyle.

`hexo server` fails with errors:

INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: watch /home/max/repos/blog/max-white-github-io/themes/tranquilpeak/node_modules/es5-ext/test/function/valid-function.js ENOSPC
    at _errnoException (util.js:1041:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/max/repos/blog/max-white-github-io/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/max/repos/blog/max-white-github-io/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/max/repos/blog/max-white-github-io/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/max/repos/blog/max-white-github-io/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/max/repos/blog/max-white-github-io/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:153:5)

on the next run:

INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: watch /home/max/repos/blog/max-white-github-io/themes/tranquilpeak/node_modules/cssstyle/lib/properties/glyphOrientationHorizontal.js ENOSPC
    at _errnoException (util.js:1041:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/max/repos/blog/max-white-github-io/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/max/repos/blog/max-white-github-io/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/max/repos/blog/max-white-github-io/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/max/repos/blog/max-white-github-io/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/max/repos/blog/max-white-github-io/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:153:5)

**Comment by max-white** [comment]
okay i fixed it with this command:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
according to this site : https://hexo.io/docs/troubleshooting.html#ENOSPC-Error-Linux
