### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by qiurigao** [LouisBarranqueiro/hexo-theme-tranquilpeak#447]
bash-4.4$ hexo v
ERROR Script load failed: themes/tranquilpeak/scripts/migrators/1.4.0.js
Error: Cannot find module 'i'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get (/data/data/com.termux/files/home/blog/themes/tranquilpeak/node_modules/utile/lib/index.js:41:30)
    at Object.<anonymous> (/data/data/com.termux/files/home/blog/themes/tranquilpeak/node_modules/utile/lib/index.js:281:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/data/com.termux/files/home/blog/themes/tranquilpeak/node_modules/prompt/lib/prompt.js:10:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (/data/data/com.termux/files/home/blog/node_modules/hexo/lib/hexo/index.js:216:21)
    at /data/data/com.termux/files/home/blog/themes/tranquilpeak/scripts/migrators/1.4.0.js:7:16
ERROR Script load failed: themes/tranquilpeak/scripts/tags/tabbed_codeblock.js
Error: Cannot find module 'whatwg-url'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/data/com.termux/files/home/blog/themes/tranquilpeak/node_modules/jsdom/lib/jsdom/utils.js:3:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/data/com.termux/files/home/blog/themes/tranquilpeak/node_modules/jsdom/lib/jsdom.js:10:43)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (/data/data/com.termux/files/home/blog/node_modules/hexo/lib/hexo/index.js:216:21)
    at /data/data/com.termux/files/home/blog/themes/tranquilpeak/scripts/tags/tabbed_codeblock.js:6:13
    at /data/data/com.termux/files/home/blog/node_modules/hexo/lib/hexo/index.js:232:12
hexo: 3.3.9
hexo-cli: 1.0.3
os: Linux 3.18.24-perf-gb4ccf5e android arm
http_parser: 2.7.0
node: 6.11.3
v8: 5.1.281.107
uv: 1.11.0
zlib: 1.2.8
ares: 1.13.0
modules: 48
openssl: 1.0.2l
bash-4.4$

**Comment by LouisBarranqueiro** [comment]
Hey @qiurigao , please follow the template and use english when you are posting an issue.
