### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by jcayzac** [LouisBarranqueiro/hexo-theme-tranquilpeak#493]
### Configuration

 - **Operating system with version** : macOS 10.13.5
 - **Node version**: 10.5.0
 - **Hexo version**: 3.2.0
 - **Hexo-cli version**: 1.1.0
 - **Tranquilpeak version**: 2.0.0 original
 
### Actual behavior
```
themes/tranquilpeak $ yarn run prod
yarn run v1.7.0
$ npm run grunt -- buildProd

> hexo-theme-tranquilpeak@2.0.0 grunt /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak
> ./node_modules/grunt-cli/bin/grunt "buildProd"

Running "clean:build" (clean) task
>> 1 path cleaned.

Running "copy:dev" (copy) task
Copied 12 files

Running "sass:dev" (sass) task

Running "concat:devJs" (concat) task

Running "sync:dev" (sync) task
Warning: Cannot read property 'bigint' of undefined Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! hexo-theme-tranquilpeak@2.0.0 grunt: `./node_modules/grunt-cli/bin/grunt "buildProd"`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the hexo-theme-tranquilpeak@2.0.0 grunt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jcayzac/.npm/_logs/2018-07-06T15_00_49_719Z-debug.log
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected behavior
Build completes without error.

### Steps to reproduce the behavior
```
$ yarn run prod
```

**Comment by jcayzac** [comment]
More logs…

```
yarn run v1.7.0
$ ./node_modules/grunt-cli/bin/grunt buildProd --verbose
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-contrib-clean" local Npm module tasks.
Reading /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-clean/package.json...OK
Parsing /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-clean/package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-concat" local Npm module tasks.
Reading /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-concat/package.json...OK
Parsing /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-concat/package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-contrib-copy" local Npm module tasks.
Reading /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-copy/package.json...OK
Parsing /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-copy/package.json...OK
Loading "copy.js" tasks...OK
+ copy

Registering "grunt-contrib-cssmin" local Npm module tasks.
Reading /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-cssmin/package.json...OK
Parsing /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-cssmin/package.json...OK
Loading "cssmin.js" tasks...OK
+ cssmin

Registering "grunt-text-replace" local Npm module tasks.
Reading /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-text-replace/package.json...OK
Parsing /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-text-replace/package.json...OK
Loading "text-replace.js" tasks...OK
+ replace

Registering "grunt-sails-linker" local Npm module tasks.
Reading /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-sails-linker/package.json...OK
Parsing /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-sails-linker/package.json...OK
Loading "scriptlinker.js" tasks...OK
+ sails-linker

Registering "grunt-sass" local Npm module tasks.
Reading /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-sass/package.json...OK
Parsing /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-sass/package.json...OK

node-sass	4.9.1	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]

Loading "sass.js" tasks...OK
+ sass

Registering "grunt-sync" local Npm module tasks.
Reading /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-sync/package.json...OK
Parsing /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-sync/package.json...OK
Loading "sync.js" tasks...OK
+ sync

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-uglify/package.json...OK
Parsing /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-uglify/package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-watch" local Npm module tasks.
Reading /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-watch/package.json...OK
Parsing /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-contrib-watch/package.json...OK
Loading "watch.js" tasks...OK
+ watch
Loading "Gruntfile.js" tasks...OK
+ build, buildProd, compileAssets, default, eslint, linkAssets, linkAssetsProd, syncAssets

Running tasks: buildProd

Running "buildProd" task

Running "clean:build" (clean) task
Verifying property clean.build exists in config...OK
Files: source/assets -> build
Options: force=false, no-write=false
Cleaning source/assets...
>> 1 path cleaned.

Running "copy:dev" (copy) task
Verifying property copy.dev exists in config...OK
Files: ./node_modules/@fancyapps/fancybox/dist/jquery.fancybox.css -> source/assets/css/jquery.fancybox.css
Files: ./node_modules/@fancyapps/fancybox/dist/jquery.fancybox.js -> source/assets/js/jquery.fancybox.js
Files: ./node_modules/@fancyapps/fancybox/src/js/thumbs.js -> source/assets/js/thumbs.js
Files: ./node_modules/@fancyapps/fancybox/src/css/thumbs.css -> source/assets/css/thumbs.css
Files: ./node_modules/font-awesome/css/font-awesome.css -> source/assets/css/font-awesome.css
Files: ./node_modules/font-awesome/fonts/fontawesome-webfont.eot -> source/assets/fonts/fontawesome-webfont.eot
Files: ./node_modules/font-awesome/fonts/fontawesome-webfont.svg -> source/assets/fonts/fontawesome-webfont.svg
Files: ./node_modules/font-awesome/fonts/fontawesome-webfont.ttf -> source/assets/fonts/fontawesome-webfont.ttf
Files: ./node_modules/font-awesome/fonts/fontawesome-webfont.woff -> source/assets/fonts/fontawesome-webfont.woff
Files: ./node_modules/font-awesome/fonts/fontawesome-webfont.woff2 -> source/assets/fonts/fontawesome-webfont.woff2
Files: ./node_modules/font-awesome/fonts/FontAwesome.otf -> source/assets/fonts/FontAwesome.otf
Files: ./node_modules/jquery/dist/jquery.js -> source/assets/js/jquery.js
Options: encoding="utf8", processContent=false, processContentExclude=[], timestamp=false, mode=false
Copying ./node_modules/@fancyapps/fancybox/dist/jquery.fancybox.css -> source/assets/css/jquery.fancybox.css
Reading ./node_modules/@fancyapps/fancybox/dist/jquery.fancybox.css...OK
Writing source/assets/css/jquery.fancybox.css...OK
Copying ./node_modules/@fancyapps/fancybox/dist/jquery.fancybox.js -> source/assets/js/jquery.fancybox.js
Reading ./node_modules/@fancyapps/fancybox/dist/jquery.fancybox.js...OK
Writing source/assets/js/jquery.fancybox.js...OK
Copying ./node_modules/@fancyapps/fancybox/src/js/thumbs.js -> source/assets/js/thumbs.js
Reading ./node_modules/@fancyapps/fancybox/src/js/thumbs.js...OK
Writing source/assets/js/thumbs.js...OK
Copying ./node_modules/@fancyapps/fancybox/src/css/thumbs.css -> source/assets/css/thumbs.css
Reading ./node_modules/@fancyapps/fancybox/src/css/thumbs.css...OK
Writing source/assets/css/thumbs.css...OK
Copying ./node_modules/font-awesome/css/font-awesome.css -> source/assets/css/font-awesome.css
Reading ./node_modules/font-awesome/css/font-awesome.css...OK
Writing source/assets/css/font-awesome.css...OK
Copying ./node_modules/font-awesome/fonts/fontawesome-webfont.eot -> source/assets/fonts/fontawesome-webfont.eot
Reading ./node_modules/font-awesome/fonts/fontawesome-webfont.eot...OK
Writing source/assets/fonts/fontawesome-webfont.eot...OK
Copying ./node_modules/font-awesome/fonts/fontawesome-webfont.svg -> source/assets/fonts/fontawesome-webfont.svg
Reading ./node_modules/font-awesome/fonts/fontawesome-webfont.svg...OK
Writing source/assets/fonts/fontawesome-webfont.svg...OK
Copying ./node_modules/font-awesome/fonts/fontawesome-webfont.ttf -> source/assets/fonts/fontawesome-webfont.ttf
Reading ./node_modules/font-awesome/fonts/fontawesome-webfont.ttf...OK
Writing source/assets/fonts/fontawesome-webfont.ttf...OK
Copying ./node_modules/font-awesome/fonts/fontawesome-webfont.woff -> source/assets/fonts/fontawesome-webfont.woff
Reading ./node_modules/font-awesome/fonts/fontawesome-webfont.woff...OK
Writing source/assets/fonts/fontawesome-webfont.woff...OK
Copying ./node_modules/font-awesome/fonts/fontawesome-webfont.woff2 -> source/assets/fonts/fontawesome-webfont.woff2
Reading ./node_modules/font-awesome/fonts/fontawesome-webfont.woff2...OK
Writing source/assets/fonts/fontawesome-webfont.woff2...OK
Copying ./node_modules/font-awesome/fonts/FontAwesome.otf -> source/assets/fonts/FontAwesome.otf
Reading ./node_modules/font-awesome/fonts/FontAwesome.otf...OK
Writing source/assets/fonts/FontAwesome.otf...OK
Copying ./node_modules/jquery/dist/jquery.js -> source/assets/js/jquery.js
Reading ./node_modules/jquery/dist/jquery.js...OK
Writing source/assets/js/jquery.js...OK
Copied 12 files

Running "syncAssets" task

Running "compileAssets" task

Running "sass:dev" (sass) task
Verifying property sass.dev exists in config...OK
Files: source/_css/tranquilpeak.scss -> source/assets/css/tranquilpeak.css
Options: precision=10, sourceMap=false
Writing source/assets/css/tranquilpeak.css...OK

Running "concat:devJs" (concat) task
Verifying property concat.devJs exists in config...OK
Files: source/_js/about.js, source/_js/archives-filter.js, source/_js/categories-filter.js, source/_js/codeblock-resizer.js, source/_js/fancybox.js, source/_js/header.js, source/_js/image-gallery.js, source/_js/post-bottom-bar.js, source/_js/search-modal.js, source/_js/share-options.js, source/_js/sidebar.js, source/_js/smartresize.js, source/_js/tabbed-codeblocks.js, source/_js/tags-filter.js -> source/assets/js/tranquilpeak.js
Options: separator=";", banner="", footer="", stripBanners=false, process=false, sourceMap=false, sourceMapName=undefined, sourceMapStyle="embed"
Reading source/_js/about.js...OK
Reading source/_js/archives-filter.js...OK
Reading source/_js/categories-filter.js...OK
Reading source/_js/codeblock-resizer.js...OK
Reading source/_js/fancybox.js...OK
Reading source/_js/header.js...OK
Reading source/_js/image-gallery.js...OK
Reading source/_js/post-bottom-bar.js...OK
Reading source/_js/search-modal.js...OK
Reading source/_js/share-options.js...OK
Reading source/_js/sidebar.js...OK
Reading source/_js/smartresize.js...OK
Reading source/_js/tabbed-codeblocks.js...OK
Reading source/_js/tags-filter.js...OK
Writing source/assets/js/tranquilpeak.js...OK
File source/assets/js/tranquilpeak.js created.
Running "sync:dev" (sync) task
Verifying property sync.dev exists in config...OK
Files: cover-v1.2.0.jpg, cover.jpg -> source/assets/images
Files: [no src] -> source/assets/fonts
Options: encoding="utf8", processContent=false, processContentExclude=[]
Warning: Cannot read property 'bigint' of undefined Use --force to continue.

Aborted due to warnings.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jcayzac** [comment]
And the actual error
```
Warning: Cannot read property 'bigint' of undefined Use --force to continue.
TypeError: Cannot read property 'bigint' of undefined
  at Object.stat (fs.js:795:37)
  at Object.stat (/Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/promised-io/promise.js:709:17)
  at processPair (/Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-sync/tasks/sync.js:150:28)
  at /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-sync/tasks/sync.js:61:16
  at Array.map (<anonymous>:null:null)
  at Object.<anonymous> (/Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-sync/tasks/sync.js:46:38)
  at Array.map (<anonymous>:null:null)
  at Object.<anonymous> (/Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt-sync/tasks/sync.js:38:28)
  at Object.<anonymous> (/Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt/lib/grunt/task.js:252:15)
  at Object.thisTask.fn (/Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt/lib/grunt/task.js:70:16)
  at Object.<anonymous> (/Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt/lib/util/task.js:293:12)
  at /Users/jcayzac/Desktop/BLOG/trankil/themes/tranquilpeak/node_modules/grunt/lib/util/task.js:220:11
  at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by LouisBarranqueiro** [comment]
👋 @jcayzac, This is related to the Node v10 version. It works well with v6 and v8. Thanks for the tip. I'm gonna update this package. 👍
