### ISSUE TITLE
Error when switching from default hexo theme

### ISSUE THREAD

**Issue by HEskandari** [LouisBarranqueiro/hexo-theme-tranquilpeak#494]
### Configuration

Hexo blog out of the box (the following versions):

hexo: 3.7.1
hexo-cli: 1.1.0
os: Darwin 17.6.0 darwin x64
http_parser: 2.7.0
node: 8.7.0
v8: 6.1.534.42
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

 - **Tranquilpeak version**: not modified, v3 downloaded from the release page
 
### Actual behavior
An error is displayed and the default website is not rendered. The error is for line 97 of file json_ld.js

```
   schema.keywords = config.keywords.join(', ');
```

The error is this:

```
    126|         <link rel="alternate" type="application/atom+xml" title="RSS" href="<%- url_for(config.feed.path) %>">
    127|     <% } %>
 >> 128|     <%- json_ld() %>
    129|     <%- open_graph({
    130|         type: 'blog',
    131|         twitter_id: theme.author.twitter,

config.keywords.join is not a function
    at Object.jsonLd (/Users/hadi/Projects/seesharp-hexo/themes/tranquilpeak/scripts/helpers/json_ld.js:97:41)
    at Object.wrapper [as json_ld] (/Users/hadi/Projects/seesharp-hexo/node_modules/lodash/lodash.js:4949:19)
    at eval (eval at compile (/Users/hadi/Projects/seesharp-hexo/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:160:17)
    at returnedFn (/Users/hadi/Projects/seesharp-hexo/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at Object.wrapper [as partial] (/Users/hadi/Projects/seesharp-hexo/node_modules/lodash/lodash.js:4949:19)
    at eval (eval at compile (/Users/hadi/Projects/seesharp-hexo/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:27:17)
    at returnedFn (/Users/hadi/Projects/seesharp-hexo/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at _compiled.then.result (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/theme/view.js:40:23)
    at tryCatcher (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)

Unhandled rejection TypeError: /Users/hadi/Projects/seesharp-hexo/themes/tranquilpeak/layout/layout.ejs:15
    13| <!DOCTYPE html>
    14| <html lang="<%= config.language %>">
 >> 15|     <%- partial('_partial/head') %>
    16|     <body>
    17|         <div id="blog">
    18|             <%- partial('_partial/header', {sidebarBehavior: sidebarBehavior}) %>

/Users/hadi/Projects/seesharp-hexo/themes/tranquilpeak/layout/_partial/head.ejs:128
    126|         <link rel="alternate" type="application/atom+xml" title="RSS" href="<%- url_for(config.feed.path) %>">
    127|     <% } %>
 >> 128|     <%- json_ld() %>
    129|     <%- open_graph({
    130|         type: 'blog',
    131|         twitter_id: theme.author.twitter,

config.keywords.join is not a function
    at Object.jsonLd (/Users/hadi/Projects/seesharp-hexo/themes/tranquilpeak/scripts/helpers/json_ld.js:97:41)
    at Object.wrapper [as json_ld] (/Users/hadi/Projects/seesharp-hexo/node_modules/lodash/lodash.js:4949:19)
    at eval (eval at compile (/Users/hadi/Projects/seesharp-hexo/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:160:17)
    at returnedFn (/Users/hadi/Projects/seesharp-hexo/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at Object.wrapper [as partial] (/Users/hadi/Projects/seesharp-hexo/node_modules/lodash/lodash.js:4949:19)
    at eval (eval at compile (/Users/hadi/Projects/seesharp-hexo/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:27:17)
    at returnedFn (/Users/hadi/Projects/seesharp-hexo/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at _compiled.then.result (/Users/hadi/Projects/seesharp-hexo/node_modules/hexo/lib/theme/view.js:40:23)
    at tryCatcher (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/hadi/Projects/seesharp-hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

### Expected behavior

Website to be rendered correctly.

### Steps to reproduce the behavior

- Create a default Hexo website (comes with one page)
- Install the tranquilpeak v3 theme.
- Run the website

**Comment by HEskandari** [comment]
Found out that the issue was how the keywords were being rendered. Changing them according to [this](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/DOCUMENTATION.md#define-global-keywords) fixed the issue.

**Comment by LouisBarranqueiro** [comment]
:wave: @HEskandari 

Yes, `keywords` are a list of string. Great that you solved this by yourself.
