### ISSUE TITLE
Cannot run the blog with tranquilpeak

### ISSUE THREAD

**Issue by karthikchintala1** [LouisBarranqueiro/hexo-theme-tranquilpeak#504]
### Configuration

 - **Operating system with version** :  Windows 10
 - **Node version**: 8.9.0
 - **Hexo version**: 3.7.1
 - **Hexo-cli version**: 1.1.0
 - **Tranquilpeak version**:  original 
 - **Site configuration file** (Optional):
 - **Theme configuration file** (Optional):
 - **Hexo plugin** (Optional): 
 
### Actual behavior
I'm getting a script error when ran hexo server command
`ERROR Script load failed: themes\tranquilpeak\scripts\tags\tabbed_codeblock.js
Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (G:\hexoblog\node_modules\hexo\lib\hexo\index.js:219:21)
    at G:\hexoblog\themes\tranquilpeak\scripts\tags\tabbed_codeblock.js:6:13
    at fs.readFile.then.script (G:\hexoblog\node_modules\hexo\lib\hexo\index.js:232:12)
    at tryCatcher (G:\hexoblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\hexoblog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (G:\hexoblog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\hexoblog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\hexoblog\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (G:\hexoblog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (G:\hexoblog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (G:\hexoblog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (G:\hexoblog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\hexoblog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\hexoblog\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (G:\hexoblog\node_modules\bluebird\js\release\promise.js:638:18)
    at G:\hexoblog\node_modules\bluebird\js\release\nodeback.js:42:21
    at G:\hexoblog\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)`

Though it shows error I have a link to localhost:4000, when accessed it is giving the following exception.
`Unhandled rejection TypeError: G:\hexoblog\themes\tranquilpeak\layout\layout.ejs:15
    13| <!DOCTYPE html>
    14| <html lang="<%= config.language %>">
 >> 15|     <%- partial('_partial/head') %>
    16|     <body>
    17|         <div id="blog">
    18|             <%- partial('_partial/header', {sidebarBehavior: sidebarBehavior}) %>

G:\hexoblog\themes\tranquilpeak\layout\_partial\head.ejs:128
    126|         <link rel="alternate" type="application/atom+xml" title="RSS" href="<%- url_for(config.feed.path) %>">
    127|     <% } %>
 >> 128|     <%- json_ld() %>
    129|     <%- open_graph({
    130|         type: 'blog',
    131|         twitter_id: theme.author.twitter,

config.keywords.join is not a function
    at Object.jsonLd (G:\hexoblog\themes\tranquilpeak\scripts\helpers\json_ld.js:97:41)
    at Object.wrapper [as json_ld] (G:\hexoblog\node_modules\lodash\lodash.js:4935:19)
    at eval (eval at compile (G:\hexoblog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:160:17)
    at returnedFn (G:\hexoblog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (G:\hexoblog\node_modules\hexo\lib\theme\view.js:120:22)
    at Theme._View.View.View.renderSync (G:\hexoblog\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (G:\hexoblog\node_modules\hexo\lib\plugins\helper\partial.js:39:15)
    at Object.wrapper [as partial] (G:\hexoblog\node_modules\lodash\lodash.js:4935:19)
    at eval (eval at compile (G:\hexoblog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:27:17)
    at returnedFn (G:\hexoblog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (G:\hexoblog\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (G:\hexoblog\node_modules\hexo\lib\theme\view.js:29:15)
    at _compiled.then.result (G:\hexoblog\node_modules\hexo\lib\theme\view.js:40:23)
    at tryCatcher (G:\hexoblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\hexoblog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (G:\hexoblog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\hexoblog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\hexoblog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (G:\hexoblog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (G:\hexoblog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (G:\hexoblog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (G:\hexoblog\node_modules\bluebird\js\release\async.js:17:14)

Unhandled rejection TypeError: G:\hexoblog\themes\tranquilpeak\layout\layout.ejs:15
    13| <!DOCTYPE html>
    14| <html lang="<%= config.language %>">
 >> 15|     <%- partial('_partial/head') %>
    16|     <body>
    17|         <div id="blog">
    18|             <%- partial('_partial/header', {sidebarBehavior: sidebarBehavior}) %>

G:\hexoblog\themes\tranquilpeak\layout\_partial\head.ejs:128
    126|         <link rel="alternate" type="application/atom+xml" title="RSS" href="<%- url_for(config.feed.path) %>">
    127|     <% } %>
 >> 128|     <%- json_ld() %>
    129|     <%- open_graph({
    130|         type: 'blog',
    131|         twitter_id: theme.author.twitter,

config.keywords.join is not a function
    at Object.jsonLd (G:\hexoblog\themes\tranquilpeak\scripts\helpers\json_ld.js:97:41)
    at Object.wrapper [as json_ld] (G:\hexoblog\node_modules\lodash\lodash.js:4935:19)
    at eval (eval at compile (G:\hexoblog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:160:17)
    at returnedFn (G:\hexoblog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (G:\hexoblog\node_modules\hexo\lib\theme\view.js:120:22)
    at Theme._View.View.View.renderSync (G:\hexoblog\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (G:\hexoblog\node_modules\hexo\lib\plugins\helper\partial.js:39:15)
    at Object.wrapper [as partial] (G:\hexoblog\node_modules\lodash\lodash.js:4935:19)
    at eval (eval at compile (G:\hexoblog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:27:17)
    at returnedFn (G:\hexoblog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (G:\hexoblog\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (G:\hexoblog\node_modules\hexo\lib\theme\view.js:29:15)
    at _compiled.then.result (G:\hexoblog\node_modules\hexo\lib\theme\view.js:40:23)
    at tryCatcher (G:\hexoblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\hexoblog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (G:\hexoblog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\hexoblog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\hexoblog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (G:\hexoblog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (G:\hexoblog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (G:\hexoblog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (G:\hexoblog\node_modules\bluebird\js\release\async.js:17:14)

Unhandled rejection TypeError: G:\hexoblog\themes\tranquilpeak\layout\layout.ejs:15
    13| <!DOCTYPE html>
    14| <html lang="<%= config.language %>">
 >> 15|     <%- partial('_partial/head') %>
    16|     <body>
    17|         <div id="blog">
    18|             <%- partial('_partial/header', {sidebarBehavior: sidebarBehavior}) %>

G:\hexoblog\themes\tranquilpeak\layout\_partial\head.ejs:128
    126|         <link rel="alternate" type="application/atom+xml" title="RSS" href="<%- url_for(config.feed.path) %>">
    127|     <% } %>
 >> 128|     <%- json_ld() %>
    129|     <%- open_graph({
    130|         type: 'blog',
    131|         twitter_id: theme.author.twitter,

config.keywords.join is not a function
    at Object.jsonLd (G:\hexoblog\themes\tranquilpeak\scripts\helpers\json_ld.js:97:41)
    at Object.wrapper [as json_ld] (G:\hexoblog\node_modules\lodash\lodash.js:4935:19)
    at eval (eval at compile (G:\hexoblog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:160:17)
    at returnedFn (G:\hexoblog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (G:\hexoblog\node_modules\hexo\lib\theme\view.js:120:22)
    at Theme._View.View.View.renderSync (G:\hexoblog\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (G:\hexoblog\node_modules\hexo\lib\plugins\helper\partial.js:39:15)
    at Object.wrapper [as partial] (G:\hexoblog\node_modules\lodash\lodash.js:4935:19)
    at eval (eval at compile (G:\hexoblog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:27:17)
    at returnedFn (G:\hexoblog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (G:\hexoblog\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (G:\hexoblog\node_modules\hexo\lib\theme\view.js:29:15)
    at _compiled.then.result (G:\hexoblog\node_modules\hexo\lib\theme\view.js:40:23)
    at tryCatcher (G:\hexoblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\hexoblog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (G:\hexoblog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\hexoblog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\hexoblog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (G:\hexoblog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (G:\hexoblog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (G:\hexoblog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (G:\hexoblog\node_modules\bluebird\js\release\async.js:17:14)
`

### Expected behavior
Should be able to see the it run

### Steps to reproduce the behavior
Didn't change much except changing the theme name in the main config.yml

**Comment by karthikchintala1** [comment]
Figured out that I have to install jsdom, jquery. So, went into themes folder and ran `npm install` to install and its working. 

But the styles on the page are not displaying properly. Not sure of the cause. Will log another issue
