### ISSUE TITLE
Can not find jsdom in Netlify

### ISSUE THREAD

**Issue by tienhm0202** [LouisBarranqueiro/hexo-theme-tranquilpeak#623]
### Description
I used hexo generate in my PC is OK, but in Netlify CI - it raised error about not found jsdom

### Expected behavior
Running `hexo generate` in Netlify CI:

```
9:07:52 AM: (node:1963) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
9:07:52 AM: ERROR Script load failed: themes/tranquilpeak/scripts/tags/tabbed_codeblock.js
9:07:52 AM: Error: Cannot find module 'jsdom'
9:07:52 AM:     at Function.Module._resolveFilename (module.js:548:15)
9:07:52 AM:     at Function.Module._load (module.js:475:25)
9:07:52 AM:     at Module.require (module.js:597:17)
9:07:52 AM:     at require (/opt/build/repo/node_modules/hexo/lib/hexo/index.js:219:21)
9:07:52 AM:     at /opt/build/repo/themes/tranquilpeak/scripts/tags/tabbed_codeblock.js:6:13
9:07:52 AM:     at fs.readFile.then.script (/opt/build/repo/node_modules/hexo/lib/hexo/index.js:232:12)
9:07:52 AM:     at tryCatcher (/opt/build/repo/node_modules/bluebird/js/release/util.js:16:23)
9:07:52 AM:     at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/bluebird/js/release/promise.js:512:31)
9:07:52 AM:     at Promise._settlePromise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:569:18)
9:07:52 AM:     at Promise._settlePromise0 (/opt/build/repo/node_modules/bluebird/js/release/promise.js:614:10)
9:07:52 AM:     at Promise._settlePromises (/opt/build/repo/node_modules/bluebird/js/release/promise.js:694:18)
9:07:52 AM:     at Promise._fulfill (/opt/build/repo/node_modules/bluebird/js/release/promise.js:638:18)
9:07:52 AM:     at Promise._resolveCallback (/opt/build/repo/node_modules/bluebird/js/release/promise.js:432:57)
9:07:52 AM:     at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/bluebird/js/release/promise.js:524:17)
9:07:52 AM:     at Promise._settlePromise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:569:18)
9:07:52 AM:     at Promise._settlePromise0 (/opt/build/repo/node_modules/bluebird/js/release/promise.js:614:10)
9:07:52 AM:     at Promise._settlePromises (/opt/build/repo/node_modules/bluebird/js/release/promise.js:694:18)
9:07:52 AM:     at Promise._fulfill (/opt/build/repo/node_modules/bluebird/js/release/promise.js:638:18)
9:07:52 AM:     at /opt/build/repo/node_modules/bluebird/js/release/nodeback.js:42:21
9:07:52 AM:     at /opt/build/repo/node_modules/graceful-fs/graceful-fs.js:78:16
9:07:52 AM:     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

### Steps to reproduce the bug
- Add repo to Netlify
- Build script is `hexo generate`

### Environment
 - **Operating system with version** : Ubuntu 16.04
 - **Node version**: 13.8.0
 - **Hexo version**: 3.9.0
 - **Hexo-cli version**: 2.0.0
 - **Tranquilpeak version**: 3.0.1 - original (only change text color in _css)
 - **Hexo plugin**: 
```
├── hexo@3.9.0
├── hexo-admin@2.3.0
├── hexo-algoliasearch@0.4.2
├── hexo-cli@2.0.0
├── hexo-deployer-git@2.1.0
├── hexo-fs@2.0.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-seo-friendly-sitemap@0.0.25
├── hexo-generator-tag@0.2.0
├── hexo-migrator-wordpress@0.1.2
├── hexo-oembed@0.1.6
├── hexo-pwa@0.1.3
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
└── hexo-web-push-notification@0.2.2
```

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋@tienhm0202,   It means that `jsdom` NPM module is not installed. Make sure you install NPM modules required by the theme. Performing `npm install` in `your-website/themes/tranquilpeak/` should fix the problem.

You could be interested by https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/488 and https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/475 as these are problems you could encounter later in the process. 🙂

**Comment by tienhm0202** [comment]
It worked like a charm. Thank you. I will close this issue <3
